### ISSUE TITLE
Does it support SIA-DC09 message?

### ISSUE THREAD

**Issue by KeithMorning** [tdeckers/utcar#1]
I see you can use the SIA-DCS  message, can it support SIA-DC 09 Protocol message?

**Comment by tdeckers** [comment]
I'm no expert in the SIA protocol whatsoever.  This implementation is based on my limited understanding of the messages that the alarm system exchanges with a backend system.  As such, can't help with any additional protocol support.  Feel free to take this code and improve upon it in whatever way you see fit.

**Comment by KeithMorning** [comment]
Thanks, tdeckers
